### ISSUE TITLE
Question about the citation style of the them

### ISSUE THREAD

**Issue by xw547** [kaimast/cornell-beamer#1]
Hi Kai,

First off, thank you so much for your fantastic theme! It looks fabulous:)

Also, would it be possible for me to have an idea about where you defined the style? I may need to use another style, but I haven't found where you defined these so that I may alter them.

Thank you,
Xiaohan

**Comment by xw547** [comment]
Hi Kai, 

I've figured it out. I think we can simply find it out by searching the command for citation style. 

Thank you:)

**Comment by kaimast** [comment]
Glad you figured it out!
